version: "3.8"

services:
  web:
    build: ./Anees
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - anees_static_volume:/app/staticfiles
      - anees_media_volume:/app/media
    expose:
      - 8000
    env_file:
      - ./Anees/.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - anees_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./Anees/.env.db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - anees_static_volume:/app/staticfiles
      - anees_media_volume:/app/media
    depends_on:
      - web
volumes:
  anees_postgres_data:
  anees_static_volume:
  anees_media_volume:
